---
# yaml-language-server: $schema=https://kubernetes-schemas.ergho.org/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community-charts
  namespace: flux-system
spec:
  interval: 2h
  url: https://prometheus-community.github.io/helm-charts
