---
# yaml-language-server: $schema=https://kubernetes-schemas.ergho.org/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: project-calico-charts
  namespace: flux-system
spec:
  interval: 2h
  timeout: 3m
  url: https://projectcalico.docs.tigera.io/charts
